version: "3.9"

services:
  web:
    image: "${DOCKER_SWARM_PRODUCTION}:5000/stackdemo"
    networks:
      - nginx_default
  redis:
    image: redis:alpine
    networks:
      - nginx_default
networks:
  nginx_default:
    external: true
