version: "3.9"

services:
  nginx:
    image: "${DOCKER_SWARM_PRODUCTION}:5000/nginx"
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - default
networks:
  default:
